"use client";

import { CreditCard, CheckCircle2 } from "lucide-react";
import { useManager } from "@/app/_hooks/use-organization";

const formatMoney=(amount:number,currency:string)=>new Intl.NumberFormat("en-NG",{style:"currency",currency,maximumFractionDigits:0}).format((amount||0)/100);

export default function ManagerBillingPage(){const {getDashboard,getBilling,startCheckout}=useManager();const {data:dashboard}=getDashboard();const {data}=getBilling();const subscription=dashboard?.subscription;return <main className="min-h-full bg-slate-50 p-4 md:p-8"><div className="mx-auto max-w-6xl space-y-6">
<header className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-2 text-indigo-600"><CreditCard size={18}/><span className="text-xs font-bold uppercase tracking-wider">Billing</span></div><h1 className="mt-2 text-2xl font-bold text-slate-900">Organization subscription</h1><p className="mt-1 text-sm text-slate-500">Keep subscription and payment controls out of the operational member workspace.</p></header>
<section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Current status</p><div className="mt-2 flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-3xl font-bold text-slate-900">{subscription?.planCode||"FREE"}</p><p className="text-sm text-slate-500">{subscription?.status||"EXPIRED"}{subscription?.endsAt?` · ends ${new Date(subscription.endsAt).toLocaleDateString()}`:""}</p></div><div className="rounded-xl bg-slate-50 px-4 py-3 text-sm text-slate-600">Server-verified Paystack billing</div></div></section>
<section className="grid gap-5 md:grid-cols-2">{(["INSTITUTION","ENTERPRISE"] as const).map(plan=>{const config=data?.plans?.[plan];return <div key={plan} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-lg font-bold text-slate-900">{plan}</p><p className="mt-2 text-3xl font-bold text-indigo-700">{config?.amount?formatMoney(config.amount,config.currency):"Not configured"}</p><p className="mt-1 text-xs text-slate-500">{config?.interval||"monthly"} · recurring</p><button disabled={startCheckout.isPending||!config?.paystackPlanCode} onClick={()=>startCheckout.mutate(plan)} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-slate-900 px-4 py-3 text-sm font-semibold text-white disabled:opacity-50"><CheckCircle2 size={16}/>{startCheckout.isPending?"Starting checkout…":"Choose plan"}</button></div>})}</section>
</div></main>}
