"use client";
import Link from "next/link";
import { useQuery } from "@tanstack/react-query";
import { ArrowLeft, Building2, CalendarDays, FolderKanban, Loader2, ShieldCheck, Users } from "lucide-react";
import { api } from "@/app/_lib/api-client";
const label=(v?:string)=>v?v.charAt(0)+v.slice(1).toLowerCase():"Member";
export default function OrganizationDetailsPage(){
 const {data,isLoading,error}=useQuery({queryKey:["my-organization"],queryFn:async()=> (await api.get("/organizations/me")).data?.organization});
 if(isLoading)return <div className="flex min-h-full items-center justify-center"><Loader2 className="animate-spin text-primary"/></div>;
 if(error||!data)return <main className="mx-auto max-w-3xl p-6"><div className="rounded-2xl border border-slate-200 bg-white p-8 text-center shadow-sm"><Building2 className="mx-auto h-10 w-10 text-slate-300"/><h1 className="mt-3 text-xl font-bold">No organization found</h1><p className="mt-2 text-sm text-slate-500">This account is not currently attached to an organization.</p><Link href="/" className="mt-5 inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-white"><ArrowLeft size={16}/>Back</Link></div></main>;
 return <main className="min-h-full bg-slate-50/70 p-4 text-slate-900 dark:bg-slate-950 dark:text-white md:p-8"><div className="mx-auto max-w-5xl space-y-6"><Link href="/" className="inline-flex items-center gap-2 text-xs font-semibold text-slate-500 hover:text-primary"><ArrowLeft size={14}/>Back to workspace</Link><section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="bg-primary/5 p-6 md:p-8"><div className="flex gap-5"><div className="flex h-16 w-16 shrink-0 items-center justify-center rounded-2xl bg-primary/10 text-primary"><Building2 size={30}/></div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-bold md:text-3xl">{data.name}</h1><span className="rounded-full bg-primary/10 px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-primary">{label(data.myRole)}</span></div>{data.code&&<p className="mt-1 text-xs font-bold uppercase tracking-widest text-slate-400">{data.code}</p>}<p className="mt-4 max-w-3xl text-sm leading-6 text-slate-600 dark:text-slate-300">{data.description||"Your organization workspace for research, collaboration, and academic activity."}</p></div></div></div><div className="grid gap-4 border-t border-slate-100 p-6 sm:grid-cols-2 lg:grid-cols-4 dark:border-slate-800"><Stat icon={Users} label="Members" value={data.memberCount}/><Stat icon={FolderKanban} label="Projects" value={data.projectCount}/><Stat icon={ShieldCheck} label="Your role" value={label(data.myRole)}/><Stat icon={CalendarDays} label="Joined" value={new Date(data.joinedAt).toLocaleDateString()}/></div></section><section className="grid gap-5 lg:grid-cols-2"><Info title="Your organization identity"><Row label="Organization role" value={label(data.myRole)}/><Row label="Department" value={data.myDepartment||"Not specified"}/>{data.externalRef&&<Row label="Organization reference" value={data.externalRef}/>}<Row label="Member since" value={new Date(data.joinedAt).toLocaleDateString()}/></Info><Info title="About this organization"><p className="text-sm leading-6 text-slate-600 dark:text-slate-300">{data.description||"No additional organization description has been provided."}</p></Info></section></div></main>;
}
function Stat({icon:Icon,label,value}:{icon:any;label:string;value:any}){return <div className="rounded-2xl border border-slate-100 bg-slate-50/70 p-4 dark:border-slate-800 dark:bg-slate-950/40"><Icon size={18} className="text-primary"/><p className="mt-3 text-2xl font-bold">{value}</p><p className="text-xs text-slate-500">{label}</p></div>}
function Info({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 className="text-base font-bold">{title}</h2><div className="mt-4">{children}</div></section>}
function Row({label,value}:{label:string;value:string}){return <div className="flex items-center justify-between gap-4 border-b border-slate-100 py-3 last:border-0 dark:border-slate-800"><span className="text-xs text-slate-500">{label}</span><span className="text-right text-sm font-semibold">{value}</span></div>}
